#!/usr/bin/env python
import sys
import os

CONFIG = {}

# Create project name and slug from command line parameters
name = " ".join(sys.argv[1:])
slug = "-".join(sys.argv[1:]).lower()

print name
print slug
